org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

minecraft_version=1.21.2
minecraft_version_range=[1.21.2]
neo_version=21.2.1-beta
loader_version_range=[1,)

mod_id=craftmusic
mod_name=CraftMusic
mod_license=All Rights Reserved
mod_version=1.0.0
mod_group_id=com.tqk114514.craftmusic
mod_authors=tqk114514
mod_description=A simple Minecraft built-in music player mod
